#Register_user
click_register  = "(//div//a[text()='Register'])[2]"
R_firstName = "//input[@name='firstname']"
R_LastName  = "//input[@name='lastname']"
R_email = "//input[@name='email']"
R_TelNum = "//input[@name='telephone']"
Password1 = "//input[@name='password']"
CNF_password1 = "//input[@name='confirm']"
PrivacyPolicy = "//input[@name='agree']"
R_continue =  "//input[@value='Continue']"
#Logout
Click_logout = "//div/a[text()='Logout']"
#Login
Click_login = "//div/a[text()='Login']"
Login_1 =  "//input[@value='Login']"
#Add to cart
Desktop1= "(//li/a[ text() = 'Desktops' ])[1]"
Mac1 = "//li/a[ text() = 'Mac (1)' ]"
AddTc = "//span[ text() = 'Add to Cart' ]"
ATcBtn= "//a[@title='Shopping Cart']"
Checkout = "//a[text()='Checkout']"
#wishlist
SearchBar= "//input[@name='search']"
searchicon = "//button[@class='btn btn-default btn-lg']"
ClickWishlist = "(//button[@type='button'])[11]"
TotalWishlist = "//a[@id='wishlist-total']"
ClickContinue1 = "//a[text()='Continue']"
RemoveWishlist = "//a[@data-original-title='Remove']"
ATCcompare = "//a[text()='MacBook Pro']/ancestor::div[@class='caption']/following-sibling::div[@class='button-group']//span"
ATCMac = "(//a[@href='https://naveenautomationlabs.com/opencart/index.php?route=product/product&product_id=45'])[3]"
UpdateQuantity = "//div[@class='input-group btn-block']//input"
#Checkout Scenario
ChecKout = "//a[text()='Checkout']"
FirstNameCheck = "//input[@name='firstname']"
LastNameCheck = "//input[@name='lastname']"
CompanyCheck = "//input[@name='company']"
Address1Check = "//input[@name='address_1']"
Address2Check= "//input[@name='address_2']"
CityCheck = "//input[@name='city']"
PostCodeCheck = "//input[@name='postcode']"
CountryCheck = "//select[@name='country_id']"
SelectCountryC = "//select[@name='country_id']//option[@value='99']"
RegionStateCheck  = "//select[@id='input-payment-zone']"
SelectStateC = "//select[@name='zone_id']//option[@value='1505']"
ClickContinueC1 = "//input[@value='Continue']"
ClickRadioButton1 = "(//input[@type='radio'])[2]"
ClickContinueC3 = "//div/input[@id='button-shipping-address']"
ClickContinueC4 = "(//div[@class='pull-right']//following-sibling::input[@value='Continue'])[3]"
CheckBox2 = "//input[@type='checkbox']"
ClickContinueC5 = "(//div[@class='pull-right']//following-sibling::input[@value='Continue'])[4]"
ConfirmOrder = "//input[@value='Confirm Order']"
OrderPlacText = "Your order has been placed!"